package wonyong.by.videostreaming

class Consts {

    //맨앞에 N, L은 Network 프로토콜인지 Local 프로토콜인지 구분하기위함
    // NETWORK PROTOCOLS
    val N_REQUEST_READY_FILE_TRANSFER = "N_REQUEST_READY_FILE_TRANSFER"
    val N_READY_FILE_TRANSFER = "N_READY_FILE_TRANSFER"
    val N_FILE_TRANSFER_START = "N_FILE_TRANSFER_START"
    val N_SEND_MESSAGE = "N_SEND_MESSAGE"
    val N_PLAY_VIDEO = "N_PLAY_VIDEO"

    // LOCAL PROTOCOLS
    val L_WAITING_RECEIVE = "L_WAITING_RECEIVE"
    val L_ON_CONNECT = "L_ON_CONNECT"
    val L_PLAYER_ON_CONNECT = "N_PLAYER_ON_CONNECT"

    //etcs
    val DELIMETER = "%^%"
    val NETWORK_MESSAGE_PORT = 8081
    val NETWORK_PLAYER_PORT = 8889

}